### ISSUE TITLE
CocoaPods doesn't update and install if the project has Sentry and Reteno installed

### ISSUE THREAD

**Issue by prossion** [reteno-com/reteno-flutter#1]
Platform
Flutter Mobile

Obfuscation
Disabled

Debug Info
Enabled

Doctor
[✓] Flutter (Channel stable, 3.10.2, on macOS 13.4 22F66 darwin-arm64, locale en-UA)
    • Flutter version 3.10.2 on channel stable at /Users/maximboyko/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (3 weeks ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/maximboyko/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.78.2)
    • VS Code at /Users/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (4 available)
    • Максим’s iPhone (mobile) • • ios • iOS 16.5 20F66
    • iPhone 14 (mobile)   •  • ios  • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)  • macos  • darwin-arm64   • macOS 13.4 22F66
      darwin-arm64
    • Chrome (web • chrome  • web-javascript • Google Chrome

[✓] Network resources
    • All expected network resources are available.

• No issues found!

Version
Reteno version 1.5.4
Sentry version 7.7.0

Steps to Reproduce
1. Set up flutter app with iOS deployment target of 12.
2. Install sentry_flutter and reteno_plugin
3. Try and run the app, but the build fails.

Expected Result
Success builded

Actual Result
Error:
   [!] CocoaPods could not find compatible versions for pod "SentryPrivate":
  In Podfile:
    reteno_plugin (from `.symlinks/plugins/reteno_plugin/ios`) was resolved to 0.0.1, which depends on
      Reteno (= 1.5.4) was resolved to 1.5.4, which depends on
        Sentry (= 8.2.0) was resolved to 8.2.0, which depends on
          SentryPrivate (= 8.2.0)

    sentry_flutter (from `.symlinks/plugins/sentry_flutter/ios`) was resolved to 0.0.1, which depends on
      Sentry/HybridSDK (= 8.7.3) was resolved to 8.7.3, which depends on
        SentryPrivate (= 8.7.3)

Are you willing to submit a PR?
None

**Comment by romanNakonechnyiReteno** [comment]
@prossion hi, thats unfortunate but in current version, sentry_flutter and reteno_plugin can not work together, as native ios sdk uses sentry internally and there is no version of sentry_flutter to satisfy this constraint, we are working to fix that in next plugin version. Please stay tunned and sorry for incovinience.

**Comment by prossion** [comment]
@romanNakonechnyiReteno Hi, thanks for answer, waiting for new version!)

**Comment by romanNakonechnyiReteno** [comment]
@prossion new release has been published to pub.dev v1.2.2. Please use sentry_flutter 7.8.0 to satisfy cocoa pods versions of sentry. I am closing this for now, feel free to reopen if you encounter same error again.
